package com.spectrus.chemport.AppData;

/**
 * The data information of the chemical elements.
 */
public class ElementData {

    /* Elements Listing
     * Atomic Number
     *
     * Atomic Mass
     * State at Room Temperature (0 - gas, 1 - liquid, 2 - solid, 3 - radioactive, 4 - unknown)
     * Synthetic (0 - no, 1- yes)
     */
    public double [][] element_list = new double [][] {
            {  0, 0.000,0,0},            // None
            {  1, 1.008,0,0},            // Hydrogen
            {  2, 4.003,0,0},            // Helium
            {  3, 6.940,0,0},            // Lithium
            {  4, 9.012,0,0},            // Beryllium
            {  5, 10.81,0,0},            // Boron
            {  6, 12.01,0,0},            // Carbon
            {  7, 14.01,0,0},            // Nitrogen
            {  8, 16.00,0,0},            // Oxygen
            {  9, 19.00,0,0},            // Fluorine
            { 10, 20.18,0,0},            // Neon
            { 11, 22.99,0,0},            // Sodium
            { 12, 24.31,0,0},            // Magnesium
            { 13, 26.98,0,0},            // Aluminium
            { 14, 28.09,0,0},
            { 15, 30.97,0,0},
            { 16, 32.06,0,0},
            { 17, 35.45,0,0},
            { 18, 39.95,0,0},
            { 19, 39.10,0,0},
            { 20, 40.08,0,0},
            { 21, 44.96,0,0},
            { 22, 47.88,0,0},
            { 23, 50.94,0,0},
            { 24, 52.00,0,0},
            { 25, 54.94,0,0},
            { 26, 55.85,0,0},
            { 27, 58.93,0,0},
            { 28, 58.69,0,0},
            { 29, 63.55,0,0},
            { 30, 65,39,0,0},
            { 31, 69.72,0,0},
            { 32, 72.64,0,0},
            { 33, 74.92,0,0},
            { 34, 78.96,0,0},
            { 35, 79.90,0,0},
            { 36, 83.80,0,0},
            { 37, 85.47,0,0},
            { 38, 87.62,0,0},
            { 39, 88.91,0,0},
            { 40, 91.22,0,0},
            { 41, 92.91,0,0},
            { 42, 95.96,0,0},
            { 43, 0,0,0},
            { 44, 0,0,0},
            { 45, 0,0,0},
            { 46, 0,0,0},
            { 47, 0,0,0},
            { 48, 0,0,0},
            { 49, 0,0,0},
            { 50, 0,0,0},
            { 51, 0,0,0},
            { 52, 0,0,0},
            { 53, 0,0,0},
            { 54, 0,0,0},
            { 55, 0,0,0},
            { 56, 0,0,0},
            { 57, 0,0,0},
            { 58, 0,0,0},
            { 59, 0,0,0},
            { 60, 0,0,0},
            { 61, 0,0,0},
            { 62, 0,0,0},
            { 63, 0,0,0},
            { 64, 0,0,0},
            { 65, 0,0,0},
            { 66, 0,0,0},
            { 67, 0,0,0},
            { 68, 0,0,0},
            { 69, 0,0,0},
            { 70, 0,0,0},
            { 71, 0,0,0},
            { 72, 0,0,0},
            { 73, 0,0,0},
            { 74, 0,0,0},
            { 75, 0,0,0},
            { 76, 0,0,0},
            { 77, 0,0,0},
            { 78, 0,0,0},
            { 79, 0,0,0},
            { 80, 0,0,0},
            { 81, 0,0,0},
            { 82, 0,0,0},
            { 83, 0,0,0},
            { 84, 0,0,0},
            { 85, 0,0,0},
            { 86, 0,0,0},
            { 87, 0,0,0},
            { 88, 0,0,0},
            { 89, 0,0,0},
            { 90, 0,0,0},
            { 91, 0,0,0},
            { 92, 0,0,0},
            { 93, 0,0,0},
            { 94, 0,0,0},
            { 95, 0,0,0},
            { 96, 0,0,0},
            { 97, 0,0,0},
            { 98, 0,0,0},
            { 99, 0,0,0},
            {100, 0,0,0},
            {101, 0,0,0},
            {102, 0,0,0},
            {103, 0,0,0},
            {104, 0,0,0},
            {105, 0,0,0},
            {106, 0,0,0},
            {107, 0,0,0},
            {108, 0,0,0},
            {109, 0,0,0},
            {110, 0,0,0},
            {111, 0,0,0},
            {112, 0,0,0},
            {113, 0,0,0},
            {114, 0,0,0},
            {115, 0,0,0},
            {116, 0,0,0},
            {117, 0,0,0},
            {118, 294.00,0,0},
            // ------ Cutoff ---------
            {119, 0,0,0},
            {120, 0,0,0}
    };

    public String [][] element_labels = new String [][] {
            { "", ""},
            { "H", "Hydrogen"},
            { "He", "Helium"},
            { "Li", "Lithium"},
            { "Be", "Beryllium"},
            { "B", "Boron"},
            { "C", "Carbon"},
            { "N", "Nitrogen"},
            { "O", "Oxygen"},
            { "F", "Fluorine"},
            { "Ne", "Neon"},
            { "Na", "Sodium"},
            { "Mg", "Magnesium"},
            { "Al", "Aluminium"},
            { "Si", "Silicon"},
            { "P", "Phosphorus"},
            { "S", "Sulfur"},
            { "Cl", "Chlorine"},
            { "Ar", "Argon"},
            { "K", "Potassium"},
            { "Ca", "Calcium"},
            { "Sc", "Scandium"},
            { "Ti", "Titanium"},
            { "V", "Vanadium"},
            { "Cr", "Chromium"},
            { "Mn", "Manganese"},
            { "Fe", "Iron"},
            { "Co", "Cobalt"},
            { "Ni", "Nickel"},
            { "Cu", "Copper"},
            { "Zn", "Zinc"},
            { "Ga", "Gallium"},
            { "Ge", "Germanium"},
            { "As", "Arsenic"},
            { "Se", "Selenium"},
            { "Br", "Bromine"},
            { "Kr", "Krypton"},
            { "Rb", "Rubidium"},
            { "Sr", "Strontium"},
            { "Y", "Yttrium"},
            { "Zr", "Zirconium"},
            { "Nb", "Niobium"},
            { "Mo", "Molybdenum"},
            { "Tc", "Technetium"},
            { "Ru", "Ruthenium"},
            { "Rh", "Rhodium"},
            { "Pd", "Palladium"},
            { "Ag", "Silver"},
            { "Cd", "Cadmium"},
            { "In", "Indium"},
            { "Sn", "Tin"},
            { "Sb", "Antimony"},
            { "Te", "Tellurium"},
            { "I", "Iodine"},
            { "Xe", "Xenon"},
            { "Cs", "Caesium"},
            { "Ba", "Barium"},
            { "La", "Lanthanum"},
            { "Ce", "Cerium"},
            { "Pr", "Praseodymium"},
            { "Nd", "Neodymium"},
            { "Pm", "Promethium"},
            { "Sm", "Samarium"},
            { "Eu", "Europium"},
            { "Gd", "Gadolinium"},
            { "Tb", "Terbium"},
            { "Dy", "Dysprosium"},
            { "Ho", "Holmium"},
            { "Er", "Erbium"},
            { "Tm", "Thulium"},
            { "Yb", "Ytterbium"},
            { "Lu", "Lutetium"},
            { "Hf", "Hafnium"},
            { "Ta", "Tantalum"},
            { "W", "Tungsten"},
            { "Re", "Rhenium"},
            { "Os", "Osmium"},
            { "Ir", "Iridium"},
            { "Pt", "Platinum"},
            { "Au", "Gold"},
            { "Hg", "Mercury"},
            { "Tl", "Thallium"},
            { "Pb", "Lead"},
            { "Bi", "Bismuth"},
            { "Po", "Polonium"},
            { "At", "Astatine"},
            { "Rn", "Radon"},
            { "Fr", "Francium"},
            { "Ra", "Radium"},
            { "Ac", "Actinium"},
            { "Th", "Thorium"},
            { "Pa", "Protactinium"},
            { "U", "Uranium"},
            { "Np", "Neptunium"},
            { "Pu", "Plutonium"},
            { "Am", "Americium"},
            { "Cm", "Curium"},
            { "Bk", "Berkelium"},
            { "Cf", "Californium"},
            { "Es", "Einsteinium"},
            { "Fm", "Fermium"},
            { "Md", "Mendelevium"},
            { "No", "Nobelium"},
            { "Lr", "Lawrencium"},
            { "Rf", "Rutherfordium"},
            { "Db", "Dubnium"},
            { "Sq", "Seaborgium"},
            { "Bh", "Bohrium"},
            { "Hs", "Hassium"},
            { "Mt", "Meitnerium"},
            { "Ds", "Darmstadtium"},
            { "Rg", "Roentgenium"},
            { "Cn", "Copernicium"},
            { "Uut", "Ununtrium"},
            { "Fl", "Flerovium"},
            { "Uup", "Ununpentium"},
            { "Lv", "Livermorium"},
            { "Uus", "Ununseptium"},
            { "Uuo", "Ununoctium"}
            // ------ Cutoff ---------
    };

    public String [][] element_labels_2016 = new String [][] {
            { "", ""},
            { "H", "Hydrogen"},
            { "He", "Helium"},
            { "Li", "Lithium"},
            { "Be", "Beryllium"},
            { "B", "Boron"},
            { "C", "Carbon"},
            { "N", "Nitrogen"},
            { "O", "Oxygen"},
            { "F", "Fluorine"},
            { "Ne", "Neon"},
            { "Na", "Sodium"},
            { "Mg", "Magnesium"},
            { "Al", "Aluminium"},
            { "Si", "Silicon"},
            { "P", "Phosphorus"},
            { "S", "Sulfur"},
            { "Cl", "Chlorine"},
            { "Ar", "Argon"},
            { "K", "Potassium"},
            { "Ca", "Calcium"},
            { "Sc", "Scandium"},
            { "Ti", "Titanium"},
            { "V", "Vanadium"},
            { "Cr", "Chromium"},
            { "Mn", "Manganese"},
            { "Fe", "Iron"},
            { "Co", "Cobalt"},
            { "Ni", "Nickel"},
            { "Cu", "Copper"},
            { "Zn", "Zinc"},
            { "Ga", "Gallium"},
            { "Ge", "Germanium"},
            { "As", "Arsenic"},
            { "Se", "Selenium"},
            { "Br", "Bromine"},
            { "Kr", "Krypton"},
            { "Rb", "Rubidium"},
            { "Sr", "Strontium"},
            { "Y", "Yttrium"},
            { "Zr", "Zirconium"},
            { "Nb", "Niobium"},
            { "Mo", "Molybdenum"},
            { "Tc", "Technetium"},
            { "Ru", "Ruthenium"},
            { "Rh", "Rhodium"},
            { "Pd", "Palladium"},
            { "Ag", "Silver"},
            { "Cd", "Cadmium"},
            { "In", "Indium"},
            { "Sn", "Tin"},
            { "Sb", "Antimony"},
            { "Te", "Tellurium"},
            { "I", "Iodine"},
            { "Xe", "Xenon"},
            { "Cs", "Caesium"},
            { "Ba", "Barium"},
            { "La", "Lanthanum"},
            { "Ce", "Cerium"},
            { "Pr", "Praseodymium"},
            { "Nd", "Neodymium"},
            { "Pm", "Promethium"},
            { "Sm", "Samarium"},
            { "Eu", "Europium"},
            { "Gd", "Gadolinium"},
            { "Tb", "Terbium"},
            { "Dy", "Dysprosium"},
            { "Ho", "Holmium"},
            { "Er", "Erbium"},
            { "Tm", "Thulium"},
            { "Yb", "Ytterbium"},
            { "Lu", "Lutetium"},
            { "Hf", "Hafnium"},
            { "Ta", "Tantalum"},
            { "W", "Tungsten"},
            { "Re", "Rhenium"},
            { "Os", "Osmium"},
            { "Ir", "Iridium"},
            { "Pt", "Platinum"},
            { "Au", "Gold"},
            { "Hg", "Mercury"},
            { "Tl", "Thallium"},
            { "Pb", "Lead"},
            { "Bi", "Bismuth"},
            { "Po", "Polonium"},
            { "At", "Astatine"},
            { "Rn", "Radon"},
            { "Fr", "Francium"},
            { "Ra", "Radium"},
            { "Ac", "Actinium"},
            { "Th", "Thorium"},
            { "Pa", "Protactinium"},
            { "U", "Uranium"},
            { "Np", "Neptunium"},
            { "Pu", "Plutonium"},
            { "Am", "Americium"},
            { "Cm", "Curium"},
            { "Bk", "Berkelium"},
            { "Cf", "Californium"},
            { "Es", "Einsteinium"},
            { "Fm", "Fermium"},
            { "Md", "Mendelevium"},
            { "No", "Nobelium"},
            { "Lr", "Lawrencium"},
            { "Rf", "Rutherfordium"},
            { "Db", "Dubnium"},
            { "Sq", "Seaborgium"},
            { "Bh", "Bohrium"},
            { "Hs", "Hassium"},
            { "Mt", "Meitnerium"},
            { "Ds", "Darmstadtium"},
            { "Rg", "Roentgenium"},
            { "Cn", "Copernicium"},
            { "Nh", "Nihonium"},
            { "Fl", "Flerovium"},
            { "Mc", "Moscovium"},
            { "Lv", "Livermorium"},
            { "Ts", "Tennessium"},
            { "Og", "Oganesson"}
            // ------ Cutoff ---------
    };

}
